name: Run npm check

on:
  push:
    paths:
      - 'website/**'
  pull_request:
    paths:
      - 'website/**'

jobs:
  run-check:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: website

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Run check
        run: npm run check
